export enum EventType {
  Strategy = 'Strategy',
  Production = 'Production',
  Council = 'Council',
  War = 'War',
  Special = 'Special',
}

export enum EventCard {
  FledglingEmpire = 'FledglingEmpire',
  FirstVentures = 'FirstVentures',
  EchoesOfThePast = 'EchoesOfThePast',
  ConveneTheCouncil = 'ConveneTheCouncil',
  RedefineTradeRoutes = 'RedefineTradeRoutes',
  BorderConflict = 'BorderConflict',
  TowardsANewHome = 'TowardsANewHome',
  AStrongFoundation = 'AStrongFoundation',
  RelicsRediscovered = 'RelicsRediscovered',
  MaximumYield = 'MaximumYield',
  TechnologicalFrontier = 'TechnologicalFrontier',
  BorderDefense = 'BorderDefense',
  PartisanManeuvering = 'PartisanManeuvering',
  WhenDiplomacyFails = 'WhenDiplomacyFails',
  BustlingEconomies = 'BustlingEconomies',
  RightfulClaim = 'RightfulClaim',
  ForbiddenKnowledge = 'ForbiddenKnowledge',
  DesperateMeasures = 'DesperateMeasures',
  IndustrialZeal = 'IndustrialZeal',
  TheLimitsOfDiplomacy = 'TheLimitsOfDiplomacy',
  DivideAndConquer = 'DivideAndConquer',
  GirdedForWar = 'GirdedForWar ',
  MercilessAmbition = 'MercilessAmbition',
  EmpireAscendant = 'EmpireAscendant',
  AThroneForTheTaking = 'AThroneForTheTaking',
}
